[package]
name = "unicode-tipa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.16"
# serde = {version = "1.0.140", features = ["derive"]}
serde_json = {version = "1.0.82", features = ["std"]}
kmp = "0.1.1"